export const CBC_TESTS = [
  {
    name: "Hemoglobin",
    aliases: ["Haemoglobin"],
    unit: "g/dL",
    referenceRange: "13.5-17.5",
    min: 13.5,
    max: 17.5,
  },
  {
    name: "WBC",
    aliases: ["WBCs"],
    unit: "x10^3/#L",
    referenceRange: "4.0-11.0",
    min: 4.0,
    max: 11.0,
  },
  {
    name: "RBC",
    aliases: ["RBCs"],
    unit: "x10#/L",
    referenceRange: "4.5-6.0",
    min: 4.5,
    max: 6.0,
  },
  {
    name: "Platelets",
    aliases: [],
    unit: "x10^3/#L",
    referenceRange: "150-450",
    min: 150,
    max: 450,
  },
  {
    name: "Hematocrit",
    aliases: ["Haematocrit"],
    unit: "%",
    referenceRange: "40-52",
    min: 40,
    max: 52,
  },
  {
    name: "MCV",
    aliases: ["M.C.V."],
    unit: "fL",
    referenceRange: "80-100",
    min: 80,
    max: 100,
  },
  {
    name: "MCH",
    aliases: ["M.C.H."],
    unit: "pg",
    referenceRange: "27-33",
    min: 27,
    max: 33,
  },
  {
    name: "MCHC",
    aliases: ["M.C.H.C."],
    unit: "g/dL",
    referenceRange: "32-36",
    min: 32,
    max: 36,
  },
  {
    name: "Neutrophils",
    aliases: [],
    unit: "%",
    referenceRange: "40-70",
    min: 40,
    max: 70,
  },
  {
    name: "Lymphocytes",
    aliases: [],
    unit: "%",
    referenceRange: "20-40",
    min: 20,
    max: 40,
  },
]; 